### ISSUE TITLE
Type safety?

### ISSUE THREAD

**Issue by pkamenarsky** [AtnNn/haskell-rethinkdb#60]
I'm wondering what it would take to make `haskell-rethinkdb` typesafe? For example, with a "result type" added to `Expr`:

    filter :: (Expr predicate (a -> Bool), Expr seq [a]) => predicate -> seq -> ReQL

So far the types don't check out, I'm trying a type family approach now. Has any work been done in that direction?

**Comment by AtnNn** [comment]
In early versions of this driver I tried to type ReQL expressions. For example [`filter`](https://github.com/AtnNn/haskell-rethinkdb/blob/40712f21a4ac4f872f9e69221d8c9a4663db229a/Database/RethinkDB/Functions.hs#L96):

```
filter :: (ToMapping m, ToStream e,
           MappingFrom m `HasToStreamValueOf` e) =>
          m -> e -> Expr (ExprType e)
```

However I ran into many problems because ReQL is inherently dynamic and output types are unpredictable and often change between versions of the server.

The [`rethinkdb-client-driver`](https://hackage.haskell.org/package/rethinkdb-client-driver) package is written with a focus on type saftety. It takes [another approach](https://github.com/wereHamster/rethinkdb-client-driver/blob/master/src/Database/RethinkDB/Types.hs#L433):

```
data Exp a where
  ... |
  Filter :: (IsSequence s) => (Exp a -> Exp Bool) -> Exp s -> Exp s
```

**Comment by pkamenarsky** [comment]
I see, thanks for the pointer!
