### ISSUE TITLE
GHC 8.0.1 support / Stackage nightly

### ISSUE THREAD

**Issue by seanhess** [AtnNn/haskell-rethinkdb#63]
Hi guys! It looks like Stackage just started supporting GHC 8.0.1, and I'm really excited for DuplicateRecordFields. 

Rethinkdb isn't listed in the stackage nightly: https://www.stackage.org/nightly-2016-05-27. I'm assuming it's because it doesn't compile with 8.0.1? What needs to be done to get it into stackage nightly and how can I help?

**Comment by codedmart** [comment]
@seanhess I honestly haven't tried to compile with GHC 8 yet. Have you? I can try later today.

**Comment by seanhess** [comment]
No, I was checking to see if I could upgrade a project and was missing this dependency. I'll let you know if I try it out before you.

**Comment by codedmart** [comment]
@seanhess I have tested locally with GHC 8.0.1. All tests pass, there is just one warning that we can suppress since we will continue to support < 7.10. Pushed a few changes to a separate branch to check against travis. If all goes well I will do a release. Keep in mind that this repo is targeted against rethinkdb 2.2 currently. The change the 2.3 have not been implemented yet.

**Comment by codedmart** [comment]
OK released http://hackage.haskell.org/package/rethinkdb-2.2.0.5. Closing for now but please feel free to reopen if there is anything wrong.

**Comment by seanhess** [comment]
Great thanks Brandon!
